sudo: required
service:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/pash.bash.inc
  - gcloud components updata kubectl
  - gcloud auth activate-servide-account --key-file service-account.json
  - gcloud config set project multi-k8s-244416
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster	
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wahoo66/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wahoo66/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master