apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nablleague-com-tls
spec:
  secretName: nablleague-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nablleague.com
  dnsNames:
    - nablleague.com
    - www.nablleague.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - nablleague.com
          - www.nablleague.com
